const $ = id => document.getElementById(id);
const send = m => chrome.runtime.sendMessage(m).then(r => { if (r.error) throw new Error(r.error); return r.ok; });
const render = async () => {
  document.title = 'keycraft ' + chrome.runtime.getManifest().version; const v = document.getElementById('ver'); if (v) v.textContent = 'v' + chrome.runtime.getManifest().version;
  let st; try { st = await send({ op: 'status' }); } catch (e) { $('lk-err').textContent = 'worker: ' + String(e.message || e) + ' (reload the extension at chrome://extensions)'; $('locked').hidden = false; $('open').hidden = true; return; }
  $('locked').hidden = st.unlocked; $('open').hidden = !st.unlocked;
  $('lk-msg').textContent = st.initialised ? 'Enter your PIN.' : 'Pick a PIN (4 to 12 digits): it seals the store on this device and on every device your Chrome profile syncs to. Nothing can open the store without it.'; $('forgot').hidden = !st.initialised;
  if (!st.unlocked) return;
  const list = await send({ op: 'listAll' }); const box = $('list'); box.replaceChildren();
  if (!list.length) box.append(Object.assign(document.createElement('p'), { className: 'muted', textContent: 'empty: save an identity from keycraft on a node' }));
  const ap = await send({ op: 'listApprovals' }); const apps = Object.keys(ap); const ab = $('apps'); ab.replaceChildren(); if (apps.length) { ab.append(document.createTextNode('apps allowed: ')); for (const a of apps) { const x = document.createElement('a'); x.textContent = a.slice(0, 10) + '… ✕'; x.title = 'forget this app'; x.style.cssText = 'cursor:pointer;margin-right:8px'; x.onclick = async () => { await send({ op: 'revoke', app: a }); render(); }; ab.append(x); } }
  for (const e of list) { const d = document.createElement('div'); d.className = 'id'; d.innerHTML = `<span><b></b><br><code></code></span>`; d.querySelector('b').textContent = e.name + (e.can_sign ? '' : ' (read-only)'); d.querySelector('code').textContent = (e.kind === 'river-room' ? 'River · room ' + e.room.slice(0, 12) + '… · ' : '') + e.owner.slice(0, 20) + '…'; const rn = document.createElement('button'); rn.className = 'ghost'; rn.textContent = 'Rename'; rn.onclick = async () => { const n = prompt('New name', e.name); if (n && n.trim() && n !== e.name) { await send({ op: 'rename', owner: e.owner, name: n }); render(); } }; d.append(rn); const rm = document.createElement('button'); rm.className = 'ghost'; rm.textContent = 'Remove'; rm.onclick = async () => { if (confirm(`Remove ${e.name} from the extension? Nodes that have it keep it.`)) { await send({ op: 'remove', owner: e.owner }); render(); } }; d.append(rm); box.append(d); }
};
$('create').onclick = async () => { $('err').textContent = ''; try { await send({ op: 'create', name: $('new-name').value }); $('new-name').value = ''; render(); } catch (e) { $('err').textContent = String(e.message || e); } };
$('scan').onclick = async () => { $('scan-out').textContent = 'asking the helper…'; try { const r = await send({ op: 'scanNode' }); const fresh = r.identities.filter(i => !i.here), freshRooms = (r.river_rooms || []).filter(x => !x.here); $('scan-out').textContent = `${r.identities.length} identit${r.identities.length === 1 ? 'y' : 'ies'} (${fresh.length} not here) and ${(r.river_rooms || []).length} River room${(r.river_rooms || []).length === 1 ? '' : 's'} (${freshRooms.length} not here) on the node; ${r.other_secrets} other secrets in ${r.delegates} delegates`; if ((fresh.length || freshRooms.length) && confirm(`Import ${[...fresh.map(i => i.name), ...(freshRooms.length ? [`${freshRooms.length} River room${freshRooms.length === 1 ? '' : 's'}`] : [])].join(', ')} from the node into the extension?`)) { const x = await send({ op: 'importFromNode' }); $('scan-out').textContent = `imported ${x.imported} identit${x.imported === 1 ? 'y' : 'ies'} and ${x.rooms} River room${x.rooms === 1 ? '' : 's'}`; render(); } } catch (e) { $('scan-out').textContent = (/Specified native messaging host not found/.test(String(e.message)) ? 'the helper is not installed (run keycraft-host install <this extension id>): ' : 'helper: ') + String(e.message || e); } };
// River moves as a sealed bundle file: its room keys and room state, re-keyed for the other node by the helper there
$('river-export').onclick = async () => { $('river-out').textContent = 'looking…'; try { const ds = await send({ op: 'riverDelegates' }); if (!ds.length) { $('river-out').textContent = 'no River rooms on this node'; return; } const d = ds[0]; const pw = prompt(`Password for the bundle (${d.rooms} rooms, ${d.secrets} secrets). You type it again when importing on the other machine.`); if (!pw) return; const r = await send({ op: 'exportDelegate', delegate: d.address, password: pw }); $('river-out').textContent = `written: ${r.path} (${r.secrets} secrets, ${(r.bytes / 1024).toFixed(0)} KiB). Move the file to the other machine and import it there.`; } catch (e) { $('river-out').textContent = String(e.message || e); } };
$('river-import').onclick = () => $('bundle').click();
$('bundle').onchange = async () => { const f = $('bundle').files[0]; if (!f) return; try { const pw = prompt('Password of the bundle'); if (pw == null) return; const bytes = new Uint8Array(await f.arrayBuffer()); let bin = ''; for (let i = 0; i < bytes.length; i += 0x8000) bin += String.fromCharCode.apply(null, bytes.subarray(i, i + 0x8000)); $('river-out').textContent = 'importing…'; const r = await send({ op: 'importBundle', bundle: btoa(bin), password: pw }); $('river-out').textContent = `${r.written} secrets written into ${r.data_dir} under ${r.delegate.slice(0, 10)}…; open River on this node`; } catch (e) { $('river-out').textContent = String(e.message || e); } finally { $('bundle').value = ''; } };
$('unlock').onclick = async () => { $('lk-err').textContent = ''; try { await send({ op: 'unlock', pin: $('pw').value }); $('pw').value = ''; render(); } catch (e) { const m = String(e.message || e); $('lk-err').textContent = /4 to 12/.test(m) ? m : /unknown op|Receiving end/.test(m) ? 'the worker is an old build: reload the extension at chrome://extensions' : 'wrong PIN'; } };
// reset needs no worker: the popup clears the store itself, so it works whatever build the worker is
$('forgot').onclick = async e => { e.preventDefault(); if (!confirm('Reset forgets this store and every identity in it, on this device and on every device it synced to. Identities still on a node can be scanned back in; others are gone unless you have a keyfile. Reset?')) return; try { await chrome.storage.sync.remove('box'); await chrome.storage.session.remove('jwk').catch(() => {}); await chrome.storage.local.remove('approvals'); $('pw').value = ''; $('lk-err').textContent = ''; } catch (err) { $('lk-err').textContent = 'reset failed: ' + String(err.message || err); } render(); };
$('changepin').onclick = async () => { const a = prompt('New PIN (4 to 12 digits)'); if (a == null) return; const b = prompt('Repeat the new PIN'); if (a !== b) { $('err').textContent = 'the PINs differ'; return; } try { await send({ op: 'changePin', pin: a }); $('err').textContent = 'PIN changed'; } catch (e) { $('err').textContent = String(e.message || e); } };
$('pw').onkeydown = e => { if (e.key === 'Enter') $('unlock').click(); };
$('lock').onclick = async () => { await send({ op: 'lock' }); render(); };
$('export').onclick = async () => { const box = await send({ op: 'exportFile' }); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([JSON.stringify(box)], { type: 'application/json' })); a.download = 'keycraft-keys.json'; a.click(); };
$('import').onclick = () => $('file').click();
$('file').onchange = async () => { const f = $('file').files[0]; if (!f) return; try { const box = JSON.parse(await f.text()); const pw = prompt('PIN of that keyfile'); if (pw == null) return; await send({ op: 'importFile', box, pin: pw }); render(); } catch (e) { $('err').textContent = String(e.message || e); } };
render();
