const $ = id => document.getElementById(id);
const send = m => chrome.runtime.sendMessage(m).then(r => { if (r.error) throw new Error(r.error); return r.ok; });
const render = async () => {
  const st = await send({ op: 'status' });
  $('locked').hidden = st.unlocked; $('open').hidden = !st.unlocked;
  $('lk-msg').textContent = st.initialised ? 'Unlock the key store.' : 'Pick a passphrase: it seals the store on this device and on every device your Chrome profile syncs to.';
  if (!st.unlocked) return;
  const list = await send({ op: 'list' }); const box = $('list'); box.replaceChildren();
  if (!list.length) box.append(Object.assign(document.createElement('p'), { className: 'muted', textContent: 'empty: save an identity from keycraft on a node' }));
  const ap = await send({ op: 'listApprovals' }); const apps = Object.keys(ap); const ab = $('apps'); ab.replaceChildren(); if (apps.length) { ab.append(document.createTextNode('apps allowed: ')); for (const a of apps) { const x = document.createElement('a'); x.textContent = a.slice(0, 10) + '… ✕'; x.title = 'forget this app'; x.style.cssText = 'cursor:pointer;margin-right:8px'; x.onclick = async () => { await send({ op: 'revoke', app: a }); render(); }; ab.append(x); } }
  for (const e of list) { const d = document.createElement('div'); d.className = 'id'; d.innerHTML = `<span><b></b><br><code></code></span>`; d.querySelector('b').textContent = e.name + (e.can_sign ? '' : ' (read-only)'); d.querySelector('code').textContent = e.owner.slice(0, 20) + '…'; const rn = document.createElement('button'); rn.className = 'ghost'; rn.textContent = 'Rename'; rn.onclick = async () => { const n = prompt('New name', e.name); if (n && n.trim() && n !== e.name) { await send({ op: 'rename', owner: e.owner, name: n }); render(); } }; d.append(rn); const rm = document.createElement('button'); rm.className = 'ghost'; rm.textContent = 'Remove'; rm.onclick = async () => { if (confirm(`Remove ${e.name} from the extension? Nodes that have it keep it.`)) { await send({ op: 'remove', owner: e.owner }); render(); } }; d.append(rm); box.append(d); }
};
$('create').onclick = async () => { $('err').textContent = ''; try { await send({ op: 'create', name: $('new-name').value }); $('new-name').value = ''; render(); } catch (e) { $('err').textContent = String(e.message || e); } };
$('scan').onclick = async () => { $('scan-out').textContent = 'asking the helper…'; try { const r = await send({ op: 'scanNode' }); const fresh = r.identities.filter(i => !i.here); $('scan-out').textContent = `${r.identities.length} identit${r.identities.length === 1 ? 'y' : 'ies'} on the node (${fresh.length} not here), ${r.other_secrets} other secrets in ${r.delegates} delegates`; if (fresh.length && confirm(`Import ${fresh.map(i => i.name).join(', ')} from the node into the extension?`)) { const x = await send({ op: 'importFromNode' }); $('scan-out').textContent = `imported ${x.imported}`; render(); } } catch (e) { $('scan-out').textContent = (/Specified native messaging host not found/.test(String(e.message)) ? 'the helper is not installed (run keycraft-host install <this extension id>): ' : 'helper: ') + String(e.message || e); } };
$('unlock').onclick = async () => { $('lk-err').textContent = ''; try { await send({ op: 'unlock', passphrase: $('pw').value }); $('pw').value = ''; render(); } catch (e) { $('lk-err').textContent = 'wrong passphrase'; } };
$('pw').onkeydown = e => { if (e.key === 'Enter') $('unlock').click(); };
$('lock').onclick = async () => { await send({ op: 'lock' }); render(); };
$('export').onclick = async () => { const box = await send({ op: 'exportFile' }); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([JSON.stringify(box)], { type: 'application/json' })); a.download = 'keycraft-keys.json'; a.click(); };
$('import').onclick = () => $('file').click();
$('file').onchange = async () => { const f = $('file').files[0]; if (!f) return; try { const box = JSON.parse(await f.text()); const pw = prompt('Passphrase of that keyfile'); if (pw == null) return; await send({ op: 'importFile', box, passphrase: pw }); render(); } catch (e) { $('err').textContent = String(e.message || e); } };
render();
